### ISSUE TITLE
Postal code not correct

### ISSUE THREAD

**Issue by LJStevo** [myTselection/Carbu_com#29] opened 2023-08-13 05:55 UTC
Asking for postal 9100 and getting 2070 ?
[sensor.carbu_com_super98_9100_price] = Carbu.com super98 2070 price

region 5km & 10km on postal 9100 are correct

**Comment by myTselection** [comment] 2023-08-26 15:10
Strange, I have tested 9100. Tested with both towns that can be linked to 9100. Didn't see this issue.
Also tested 2070 without any issue.
Are you sure you are on the latest release?

**Comment by myTselection** [comment] 2023-09-07 19:34
closing this one since no feedback and not reproducable. You may re-open it if needed...

**Closed by myTselection** 2023-09-07 19:34 UTC
