### ISSUE TITLE
Home assistant crash

### ISSUE THREAD

**Issue by Sarnog** [myTselection/Carbu_com#55] opened 2024-08-26 16:38 UTC
I don't know what is happening, but the moment i install version 11.1.3 via HACS and i reboot Home Assistant, Home assistant disconnects and crashes (the moment it should show home assistant is started). I can't get into home assistant again and needed to install a backup. I can't get into logs or anything, so i can't provide you anything as far as i know.

**Comment by Ocramius** [comment] 2024-08-26 16:52
@Sarnog meanwhile, my endorsement is (if you run HASSIO)

 1. attach Home Assistant to a monitor (or log in remotely, if you can)
 2. `cd /mnt/data/supervisor/homeassistant`
 3. `mkdir disabled_custom_components`
 4. `mv custom_components/carbu_com disabled_custom_components/carbu_com`
 5. `ha core restart`

**Comment by djfanatix** [comment] 2024-08-27 11:10
yep I have the same issue and I cannot find anything in the logs.

I did a terminal login, did 

ha core restart --safe-mode

and then disable carbu

**Comment by mzspicoli** [comment] 2024-08-27 11:59
Also happening with me. Tried to reinstall 2 times the VM before realizing it was some integration, probably Carbu.. looking forward to resolve this.

**Comment by myTselection** [comment] 2024-08-27 12:45
Sorry about this! My env with 6 different locations in carbu is running fine now, so I don't have a clear view on any root cause.

I'll try to publish a new release asap in which I'll remove the query request cache as this is one of the only structural changes added in R11.x.

**Comment by mzspicoli** [comment] 2024-08-27 12:48
I needed to restart in safe mode and then I removed the carbu_com folder from custom_integrations folder and it is working now.

**Comment by myTselection** [comment] 2024-08-28 16:29
anyone could confirm the startup issue is fixed with R11.1.5?  As I'm not able to reproduce this issue myself.

**Comment by Ocramius** [comment] 2024-08-28 16:58
I've just restarted my HA with Carbu `11.1.5` installed, and it fired back up! :-) 

Checked also diff: thanks for your work!

https://github.com/myTselection/Carbu_com/compare/11.1.3...11.1.5

I think the cache approach wasn't working because SQLite is locked, and your code attempts to do a second SQLite DB connection, but I totally lost the error message that highlighted this somewhere :S

**Comment by myTselection** [comment] 2024-08-28 17:28
Great, thx for the confirmation!

**Closed by myTselection** 2024-08-28 17:28 UTC
Labels: bug
